version: '3.8'
services:
  activemq:
    image: 'apache/activemq-classic:6.1.4'
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      - ACTIVEMQ_CONNECTION_USER=admin
      - ACTIVEMQ_CONNECTION_PASSWORD=password

